spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    generate-unique-name: false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    hikari:
      maximum-pool-size: 5
      connection-timeout: 600000
    username: root
    password: r12xVa_hwe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  docker:
    compose:
      enabled: false
  thymeleaf:
    enabled: true
    check-template-location: true
server:
  error:
    include-stacktrace: never
    include-message: always
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
    default-models-expand-depth: -1
  show-actuator: true
